### ISSUE TITLE
Allow to include related entities in the response

### ISSUE THREAD

**Issue by xdmx** [deanpcmad/paddle#3]
The get subscription and get transaction allow to include related entities in the response, lowering the number of requests (or in some cases, get data that wouldn't be available otherwise). For example: https://developer.paddle.com/api-reference/subscriptions/get-subscription#query-parameters

What do you think about adding an extra "include:` argument on those endpoints that support them? Maybe allowing to pass the data both as a string or an array (I think they expect them as comma separated, but I haven't tried)

**Comment by deanpcmad** [comment]
Good idea, will be pushed in the next update
