### ISSUE TITLE
Paddle::Subscription.preview with discount: null

### ISSUE THREAD

**Issue by lonhtm** [deanpcmad/paddle#4]
```ruby
Paddle::Subscription.preview(id: "sub_abc123", items: [ { price_id: "pri_123abc", quantity: 2 } ], discount: nil )
```
This will not remove the existing discount. Paddle Billing API indicate that we have to pass 
```js
discount: null
```
to remove it.

**Comment by excid3** [comment]
Ran into this tonight. Paddle says you can pass `null` to `subscription_id` for the List Transactions endpoint. This is more of an issue with their API than with the gem.

The gem correctly includes the param with no value:
```ruby
Paddle::Transaction.list(subscription_id: nil)
#=> I, [2024-01-18T20:05:58.941891 #61339]  INFO -- request: GET https://sandbox-api.paddle.com/transactions?subscription_id
#=> 400 Bad Request
```

However, Paddle's API actually wants you to pass `subscription_id=null`. So this works instead:

```ruby
Paddle::Transaction.list(subscription_id: "null")
```

The `preview` call should then be:

```ruby
Paddle::Subscription.preview(id: "sub_abc123", items: [ { price_id: "pri_123abc", quantity: 2 } ], discount: "null")
```

An argument could be made to modify the gem to translate `nil` to `"null"` for specific endpoints, but it's going to be a maintenance burden as their API changes. In the meantime, we could note this in the README as a gotcha. Thoughts @deanpcmad?

**Comment by deanpcmad** [comment]
Thanks @excid3, just added a note to the readme to say this 😄
